[metadata]
name = 'Kanagawa'

[colors]
foreground = "#dcd7ba"
background = "#1f1f28"
cursor_bg = "#c8c093"
cursor_fg = "#1f1f28"
cursor_border = "#c8c093"
selection_fg = "#c8c093"
selection_bg = "#2d4f67"
scrollbar_thumb = "#16161d"
split = "#16161d"
ansi = [
  "#16161d",
  "#c34043",
  "#76946a",
  "#c0a36e",
  "#7e9cd8",
  "#957fb8",
  "#6a9589",
  "#c8c093"
]
brights = [
  "#727169",
  "#e82424",
  "#98bb6c",
  "#e6c384",
  "#7fb4ca",
  "#938aa9",
  "#7aa89f",
  "#dcd7ba"
]

[colors.indexed]
16 = "#ffa066"
17 = "#ff5d62"
18 = "#2d4f67"


[colors.tab_bar]
background = "#16161d"
foreground = "#727169"
inactive_tab_edge = "#16161d"
inactive_tab_edge_hover = "#586069"

[colors.tab_bar.active_tab]
bg_color = "#284566"
fg_color = "#dcd7ba"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#16161d"
fg_color = "#727169"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#16161d"
fg_color = "#727169"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#16161d"
fg_color = "#727169"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#16161d"
fg_color = "#727169"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"
